### ISSUE TITLE
Candidate Recommendation readiness tracker

### ISSUE THREAD

**Issue by anssiko** [webmachinelearning/webnn#240]
This is a meta issue to track [Candidate Recommendation (CR)](https://www.w3.org/2021/Process-20211102/#RecsCR) publication readiness for the [Neural Network API](https://www.w3.org/TR/webnn/).

### About

A Candidate Recommendation is a document that satisfies the technical requirements of the [Working Group that produced it](https://www.w3.org/groups/wg/webmachinelearning) and their dependencies, and has already received wide review. W3C publishes a Candidate Recommendation to
- signal to the wider community that it is time to do a final review
- gather implementation experience

### Requirements

>Legend:
>⚪ Not started
>🟡 In progress
>🟢 Completed

To publish a Candidate Recommendation, in addition to meeting the [requirements for advancement](https://www.w3.org/2021/Process-20211102/#transition-reqs) a Working Group:

- [x] must show that the specification has met all Working Group requirements, or explain why the requirements have changed or been deferred,
   - 🟢 The document meets the requirements set forth in the [WG Charter](https://www.w3.org/2021/04/web-machine-learning-charter.html) and satisfies the [Use Cases](https://www.w3.org/TR/webnn/#usecases)
   - 🟢 The document is considered [complete and fit for purpose](https://www.w3.org/2021/Process-20211102/#ref-for-RecsCR%E2%91%A3)
   - 🟢 Remaining ["cr" issues](https://github.com/webmachinelearning/webnn/labels/cr) improve test coverage and alignment of core parts of the API with WebIDL conventions:
      - [x] https://github.com/webmachinelearning/webnn/issues/265 completed
      - [x] See "Done" in https://github.com/webmachinelearning/webnn/issues/210#issuecomment-1326361748
   - 🟡 Post-CR enhancements:
      - [ ] #338 WIP
      - [x] Complete https://github.com/webmachinelearning/webnn/issues/210 WIP
   - 🟢 [Other deliverables](https://www.w3.org/2021/04/web-machine-learning-charter.html#ig-other-deliverables): ethical considerations [documented](https://www.w3.org/TR/webmachinelearning-ethics/)
- [x] must document changes to dependencies during the development of the specification,
   - 🟢 No new [normative references](https://www.w3.org/TR/webnn/#normative) since [FPWD](https://www.w3.org/TR/2021/WD-webnn-20210622/)
- [x] must document how adequate implementation experience will be demonstrated,
   - 🟢 [web-platform-tests test suite](https://github.com/web-platform-tests/wpt/tree/master/webnn) / https://github.com/webmachinelearning/webnn/issues/265 / [wpt.fyi](https://wpt.fyi/results/webnn?label=experimental&label=master&aligned&view=subtest)
   - 🟡 Preliminary implementation reports based on one or more of:
     - 🟡 JS implementations: [webnn-baseline](https://github.com/webmachinelearning/webnn-baseline) (pure JS), [webnn-polyfill](https://github.com/webmachinelearning/webnn-polyfill) (use TF.js backends) 
     - 🟡 Chromium implementation: [Intent to Prototype](https://groups.google.com/a/chromium.org/g/blink-dev/c/PD6TDMDS9mg), [source](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/ml/webnn/), [tracker bug](https://crbug.com/1273291), [issues](https://bugs.chromium.org/p/chromium/issues/list?q=component:Blink%3EWebML), [patches](https://chromium-review.googlesource.com/q/hashtag:webnn+(status:open%20OR%20status:merged))
     - 🟡 Chromium backends: [XNNPACK](https://chromium-review.googlesource.com/c/chromium/src/+/3684745) and [DirectML](https://chromium-review.googlesource.com/c/chromium/src/+/3915513) ([design doc](https://docs.google.com/document/d/1TMs36IE9wL9rNuh8lriGr51S8MU1JezU2SCZy-YqJ3Y/))
       - Note: per Chromium dev [best practices](https://chromium.googlesource.com/chromium/src.git/+/HEAD/docs/cl_respect.md#mind-your-reviewer) the initial prototyping happens in big patches ("big CLs") but is landed in multiple small patches ("small CLs"), see the [tracker issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1273291) for the latest landed patches
- [x] must specify the deadline for comments, which must be at least 28 days after publication, and should be longer for complex documents,
- [x] must show that the specification has received wide review, and
   - 🟢 Wide review tracked in https://github.com/webmachinelearning/webnn/issues/239
   - Implementation-specific reviews of interest (informational, not a complete list):
     - 🟢 Chromium security review for [accelerated backends](https://bugs.chromium.org/p/chromium/issues/detail?id=1381569)
- [x] may identify features in the document as at risk. These features may be removed before advancement to Proposed Recommendation without a requirement to publish a new Candidate Recommendation.
   - 🟢 WebGPU interoperability [identified](https://www.w3.org/2022/11/03-webmachinelearning-minutes.html#t05) as a feature at risk for CR publication, needs more implementation experience, SOTD updated accordingly in #340

**Comment by huningxin** [comment]
I'd like to propose WebNN baseline implementation (https://github.com/webmachinelearning/webnn/issues/245) to be tracked by CR readiness. It would be used to establish the baseline for WebNN web-platform-tests.

**Comment by wchao1115** [comment]
issue #230 and #229 should also be tracked for CR readiness.

**Comment by anssiko** [comment]
Per [WebML WG Teleconference – 13 January 2022](https://www.w3.org/2022/01/13-webmachinelearning-minutes.html#t06), explicitly added to the list the following requirement:

Other deliverables: ethical considerations documented

This work in ongoing in its [own repo](https://github.com/webmachinelearning/ethical-webmachinelearning) and [is referenced from](https://www.w3.org/TR/webnn/#ethics) the WebNN API specification. The plan on how we advance this work was presented in the [WebML WG Teleconference – 16 Dec 2021](https://www.w3.org/2021/12/16-webmachinelearning-minutes.html#t03).

**Comment by anssiko** [comment]
I added webnn-baseline implementation as a new component for the adequate implementation experience requirement. The initial webnn-baseline implementation is currently in review: https://github.com/webmachinelearning/webnn-baseline/pull/1

**Comment by anssiko** [comment]
The initial [webnn-baseline implementation](https://github.com/webmachinelearning/webnn-baseline) landed. We continue refine this project to help gather implementation experience for [Candidate Recommendation](https://www.w3.org/2021/Process-20211102/#RecsCR) purposes. Another ongoing effort that contributes to implementation experience is the [Chromium WIP prototype](https://groups.google.com/a/chromium.org/g/blink-dev/c/PD6TDMDS9mg).

**Comment by anssiko** [comment]
[As discussed](https://www.w3.org/2023/01/12-webmachinelearning-minutes.html#t07), our collective goal is to add some final polish and ship the CR during Q1 2023. Thank you for your contributions!

**Comment by anssiko** [comment]
We have issued a [Call for Consensus](https://lists.w3.org/Archives/Public/public-webmachinelearning-wg/2023Feb/0005.html) to publish WebNN API Candidate Recommendation.

**Comment by anssiko** [comment]
FTR, the [Call for Consensus passes](https://lists.w3.org/Archives/Public/public-webmachinelearning-wg/2023Mar/0000.html).

Related, I preparation for the upcoming Candidate Recommendation publication I've done an issue triage. If you identify any bugs in labelling please let me know and we'll adjust. The labels are considered informative. The purpose is to make the issue list more easy to grasp for the WG as well as for other folks who might peek into our repo on their quest to make a positive impact with concrete contributions. Don't read too much into the semantics of the names of these labels.

**Comment by anssiko** [comment]
The WG is looking publish a new Candidate Recommendation Snapshot in Q1'24. Delta wide review is in flight https://github.com/webmachinelearning/webnn/issues/239#issuecomment-1911930089 and the Status of this document is staged at https://github.com/webmachinelearning/webnn/pull/532. Notably, the WG has gathered further [implementation experience](https://webmachinelearning.github.io/webnn-status/) since its previous CR publication.

**Comment by anssiko** [comment]
As [discussed](https://www.w3.org/2024/02/22-webmachinelearning-minutes.html#t02), with the recent updates to the spec, WPT and implementation status, we're getting very close to CR Snapshot readiness.

We're awaiting a go-ahead signal from the  TAG delta review to initiate the transition. Based on my assessment we satisfy all the other requirements. @dontcallmedom can you please cross-check against the latest transition request expectations that we've all set otherwise. Would it be appropriate to issue a CfC now (noting the TAG delta review is in flight)?

Thank you everyone for your major contributions that make this important publication happen!

**Comment by dontcallmedom** [comment]
yes, starting the CfC seems appropriate; if the TAG review raises new concerns, we would still have the opportunity to revisit our decision prior to submitting the transition request.

(and I confirm we're otherwise ready for the transition request)

**Comment by anssiko** [comment]
Thanks @dontcallmedom.

[Call for Consensus](https://lists.w3.org/Archives/Public/public-webmachinelearning-wg/2024Feb/0006.html) to publish a new WebNN API Candidate Recommendation Snapshot issued.

**Comment by anssiko** [comment]
The most recent [Call for Consensus passes](https://lists.w3.org/Archives/Public/public-webmachinelearning-wg/2024Mar/0000.html).

**Comment by anssiko** [comment]
CR Snapshot transition request: https://github.com/w3c/transitions/issues/592 (thanks @dontcallmedom!)

**Comment by anssiko** [comment]
I’m pleased to announce the Web Neural Network API (WebNN) has been published as a Candidate Recommendation Snapshot today:

🚀 https://www.w3.org/TR/2024/CR-webnn-20240411/

Congratulations to the WG for this major accomplishment. The publication would not have been possible without every WG participants' contributions.
